### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by hanahaneull** [kyochikuto/sing-box-plus#2]
### Operating system

Linux

### System version

6.10.7-arch1-1

### Installation type

Original sing-box Command Line

### Version

```shell
1.9.3
```

### Description

When `tls_fragment` enabled, for some website (ddos-guard) there is certificate error. Without `tls_fragment` enabled, certificate seems fine.

Example:
https://jpg5.su/
https://nyaa.si
https://cyberdrop.me/

### Reproduction

Enable `tls_fragment` on the `outbounds` array
```
{
	"type": "direct",
	"tag": "fragment",
	"tcp_fast_open": false,
	"tls_fragment": {
		"enabled": true,
		"size": "200-256",
		"sleep": "0-2"
	}
}
```

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/nekohasekai/)

### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I confirm that I have provided the server and client configuration files and process that can be reproduced locally, instead of a complicated client configuration file that has been stripped of sensitive data.
- [X] I confirm that I have provided the simplest configuration that can be used to reproduce the error I reported, instead of depending on remote servers, TUN, graphical interface clients, or other closed-source software.
- [X] I confirm that I have provided the complete configuration files and logs, rather than just providing parts I think are useful out of confidence in my own intelligence.

**Comment by kyochikuto** [comment]
Apologies for the late reply, TLS fragmentation method has been updated in the latest release, retest and report please.

**Comment by hanahaneull** [comment]
I can confirm the certificate issue now are gone.

Thank you for fixing the issue. Since I thought the issue would be the DDoS-Guard it self to defend TLS fragment attack.
